import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Registry, type Tool } from "../src/registry/index.js";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const defaultOutputPath = path.join(repoRoot, "docs", "providers.md");

export const providerCatalogBanner = [
  "<!--",
  "Generated by `pnpm run docs:providers`.",
  "Do not edit by hand; hand edits will be overwritten.",
  "-->",
  "",
].join("\n");

export async function discoverProviderTools(toolsDir?: string): Promise<Tool[]> {
  const registry = new Registry(toolsDir === undefined ? {} : { toolsDir });
  await registry.discover();
  return registry.all();
}

export function renderProvidersDoc(tools: readonly Tool[]): string {
  const sortedTools = [...tools].sort(compareTools);
  const lines = [
    providerCatalogBanner.trimEnd(),
    "",
    "# Provider Catalog",
    "",
    "This catalog is generated from the tool registry. Regenerate it after changing a tool definition:",
    "",
    "```bash",
    "pnpm run docs:providers",
    "```",
    "",
  ];

  for (const [capability, capabilityTools] of groupByCapability(sortedTools)) {
    lines.push(`## ${capability}`, "");
    lines.push("| name | status | integration | provider/binary | auth | best_for/blurb | cost |");
    lines.push("|---|---|---|---|---|---|---|");

    for (const tool of capabilityTools) {
      const cells = [
          markdownCell(code(tool.name)),
          markdownCell(tool.status),
          markdownCell(tool.integration.kind),
          markdownCell(providerOrBinary(tool)),
          markdownCell(authDescription(tool)),
          markdownCell(tool.best_for),
          markdownCell(costDescription(tool)),
        ];
      lines.push(`| ${cells.join(" | ")} |`);
    }

    lines.push("");
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

export async function writeProvidersDoc(outputPath = defaultOutputPath, toolsDir?: string): Promise<void> {
  const output = renderProvidersDoc(await discoverProviderTools(toolsDir));
  await writeFileAtomic(outputPath, output);
}

export async function checkProvidersDoc(outputPath = defaultOutputPath, toolsDir?: string): Promise<boolean> {
  const output = renderProvidersDoc(await discoverProviderTools(toolsDir));
  let current = "";

  try {
    current = await readFile(outputPath, "utf8");
  } catch (error) {
    if (!isNodeError(error) || error.code !== "ENOENT") {
      throw error;
    }
  }

  return current === output;
}

function compareTools(left: Tool, right: Tool): number {
  return (
    left.capability.localeCompare(right.capability) ||
    left.integration.kind.localeCompare(right.integration.kind) ||
    left.name.localeCompare(right.name) ||
    left.provider.localeCompare(right.provider)
  );
}

function groupByCapability(tools: readonly Tool[]): Array<[string, Tool[]]> {
  const groups = new Map<string, Tool[]>();

  for (const tool of tools) {
    const group = groups.get(tool.capability) ?? [];
    group.push(tool);
    groups.set(tool.capability, group);
  }

  return [...groups.entries()];
}

function providerOrBinary(tool: Tool): string {
  switch (tool.integration.kind) {
    case "api":
      return tool.provider;
    case "binary":
      return tool.integration.binary;
    case "cli":
      return `${tool.provider} / ${tool.integration.binary}`;
    case "library":
      return tool.integration.package;
  }
}

function authDescription(tool: Tool): string {
  const integration = tool.integration;

  switch (integration.kind) {
    case "api":
      return envDescription(integration.env);
    case "binary":
    case "library":
      return "none";
    case "cli":
      if (integration.auth.mode === "cli-login") {
        return `cli-login (${integration.auth.check})`;
      }

      if (integration.auth.mode === "env") {
        return envDescription(integration.auth.env);
      }

      return "none";
  }
}

function envDescription(env: readonly string[]): string {
  return env.length === 0 ? "none" : env.map((name) => code(name)).join(", ");
}

function costDescription(tool: Tool): string {
  if (tool.cost === undefined) {
    return "not declared";
  }

  return `$${formatUsd(tool.cost.usd)} / ${tool.cost.unit}`;
}

function formatUsd(value: number): string {
  if (value === 0) {
    return "0";
  }

  const rendered = value >= 0.01 ? value.toFixed(2) : value.toFixed(6);
  return rendered.replace(/0+$/u, "").replace(/\.$/u, "");
}

function markdownCell(value: string): string {
  return value.replaceAll("\n", "<br>").replaceAll("|", "\\|");
}

function code(value: string): string {
  return `\`${value}\``;
}

async function writeFileAtomic(filePath: string, contents: string): Promise<void> {
  await mkdir(path.dirname(filePath), { recursive: true });
  const tempPath = path.join(path.dirname(filePath), `.${path.basename(filePath)}.${process.pid}.tmp`);
  await writeFile(tempPath, contents, "utf8");
  await rename(tempPath, filePath);
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && "code" in error;
}

async function main(): Promise<void> {
  const check = process.argv.includes("--check");

  if (check) {
    const matches = await checkProvidersDoc();
    if (!matches) {
      console.error("docs/providers.md is stale. Run `pnpm run docs:providers`.");
      process.exitCode = 1;
    }
    return;
  }

  await writeProvidersDoc();
}

if (process.argv[1] !== undefined && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await main();
}
